/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ahaen' at '22.04.17 14:22' with Gradle 2.14.1
 *
 * @author ahaen, @date 22.04.17 14:22
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
